# Generated by Django 4.1 on 2022-09-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
    ]
