# Generated by Django 4.1 on 2022-09-10 14:41

import Task.models
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('TaskId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Declined', 'Declined')], default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('product_link', models.URLField()),
                ('task_reward', models.FloatField(default=0.2)),
                ('worker_score', models.IntegerField(default=0)),
                ('task_budget', models.FloatField(default=10.0)),
                ('task_active', models.BooleanField(default=True)),
                ('task_instruction', models.TextField()),
                ('conceal_product_link', models.BooleanField(default=True)),
                ('task_title', models.CharField(max_length=255)),
                ('task_duration', models.DateTimeField(default=datetime.datetime(2022, 9, 13, 14, 41, 12, 809472))),
                ('task_deadline', models.CharField(default='4hours', max_length=100)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_preview', models.ImageField(blank=True, null=True, upload_to=Task.models.task_directory_path)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('review', 'review'), ('survey', 'survey'), ('custom', 'custom'), ('download', 'download'), ('channel_boost', 'channel_boost')], default='download', max_length=100)),
                ('screenshot_proof_example', models.ImageField(blank=True, null=True, upload_to=Task.models.task_directory_path)),
                ('proof_type', models.CharField(choices=[('url_proof', 'url_proof'), ('text_proof', 'text_proof'), ('video_proof', 'video_proof'), ('screenshot_proof', 'screenshot_proof')], default='screenshot_proof', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_proof', models.ImageField(blank=True, null=True, upload_to=Task.models.task_directory_path)),
                ('video_proof', models.FileField(null=True, upload_to=Task.models.task_directory_path)),
                ('url_proof', models.URLField(blank=True)),
                ('text_proof', models.TextField(blank=True)),
            ],
        ),
    ]
