# Generated by Django 4.1 on 2022-09-10 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtasks',
            name='participant',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 14, 59, 41, 967646)),
        ),
    ]
