# Generated by Django 4.1 on 2022-09-10 15:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task', '0003_remove_completedtasks_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtasks',
            name='participant',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 15, 0, 52, 243241)),
        ),
    ]
