# Generated by Django 4.1 on 2022-09-10 16:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_completedtasks_participant_alter_task_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtasks',
            name='task_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 16, 9, 48, 467266)),
        ),
    ]
