# Generated by Django 4.1 on 2022-09-12 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_alter_task_date_created_alter_task_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount_distributed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 17, 14, 49, 51827)),
        ),
    ]
