# Generated by Django 4.1 on 2022-09-12 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_task_amount_distributed_alter_task_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='task_status',
            field=models.CharField(choices=[('Working', 'Working'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Working', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 20, 4, 9, 653813)),
        ),
    ]
