# Generated by Django 4.1 on 2022-09-12 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_alter_completedtasks_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtasks',
            name='task_review',
            field=models.CharField(choices=[('Neutral', 'Neutral'), ('Good', 'Good'), ('Bad', 'Bad')], default='Neutral', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 20, 35, 41, 781762)),
        ),
    ]
