# Generated by Django 4.1 on 2022-09-12 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0009_completedtasks_task_review_alter_task_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtasks',
            name='user_task_reward',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 20, 49, 0, 979705)),
        ),
    ]
