# Generated by Django 4.1 on 2022-09-12 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0011_alter_completedtasks_user_task_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 20, 49, 27, 224997)),
        ),
    ]
