# Generated by Django 4.1 on 2022-09-12 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0012_alter_task_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 20, 56, 39, 32505)),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker_score',
            field=models.IntegerField(default=80),
        ),
    ]
