# Generated by Django 4.1 on 2022-09-14 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0014_taskproof_proof_type_alter_task_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 2, 21, 13, 133964)),
        ),
    ]
