# Generated by Django 4.1 on 2022-09-14 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0016_remove_completedtasks_task_proof_taskproof_taskid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 22, 2, 40, 552417)),
        ),
    ]
